export const quickLinks = [
  "Home",
  "Flights",
  "About Us",
  "Travel Agency",
  "Privacy Policy",
  "Refund Policy",
  "Contact Us",
];

export const branchList = [
  "Islamabad",
  "Peshawar",
  "Lahore",
  "Dubai (UAE)",
  "United Kingdom",
];

export const contactDetails = {
  phone: "+92 51 111 786 785",
  whatsapp: "+92 311 786 785",
  email: "info@rehmantravel.com",
  address:
    "Rehman Travels Office No 3 Ground Floor, Office Tower 44 East Fazal E Haq Road Blue Area, G 6/2, Islamabad, 44000, Pakistan",
};

export const navLinks = [
  "Home",
  "Flights",
  "Hajj",
  "Umrah",
  "Study",
  "Visa",
  "World Tours",
  "Pakistan Tours",
  "About Us",
  "Contact Us",
];

export const navDropdownItems = [
  "Hajj",
  "Umrah",
  "Study",
  "Visa",
  "World Tours",
  "Pakistan Tours",
  "About Us",
];

export const navDropdownContent = {
  Hajj: [
    "Platinum Hajj Packages",
    "Hajj Packages 2025",
    "Executive Hajj Packages 2025 From Pakistan",
    "Ibadat Packages",
  ],
  Umrah: [
    "Customized Umrah packages From Pakistan",
    "Economy Umrah Packages",
    "Executive Umrah Packages",
    "Umrah Packages 2025",
    "Umrah Protocols in Pakistan",
    "Umrah e Visa From Pakistan",
    "Best Umrah Packages",
    "Ramzan Umrah Packages",
    "Umrah Guide",
    "Child Umrah Visa",
    "15 Days Umrah Packages From Pakistan",
    "Ziyarat in Makkah and Madinah",
    "Umrah Transportation Services",
    "Umrah Facilities",
  ],
  Study: [
    "China Bachelor Degree Program",
    "PHD Scholarships in China",
    "MBBS in China",
    "Malaysia International Scholarship",
    "Turkiye Burslari Scholarship",
    "Google PhD Fellowship Program",
    "Internships For International Students 2025",
    "MBA in Australia",
    "Student Visa Australia",
    "BSC Medicine in UK",
    "MBA in UK",
    "Scholarships in China - Rehman Travels",
    "Australia Scholarships",
    "Top Universities For Engineering UK",
    "UK Scholarships For International Students",
    "PHD Scholarships in Australia",
    "2 Years Bachelor Degree in Canada",
    "US Fully Funded Scholarships",
    "LLB Bachelor of Laws in UK",
    "Germany Study Visa",
    "Information Technology China",
    "MS Computer Science in UK",
    "MBA Scholarships in USA",
    "UK Student Visa",
    "Study MBBS in USA For Pakistani Students",
    "MBA Scholarships in UK",
    "MBA Scholarships in China",
    "Scholarships in Canada",
    "Fully Funded Scholarships in Saudi Arabia",
    "MBBS in Australia",
    "MBA in Canada",
    "Summer Courses in USA",
    "MBA in Australia",
    "scholarships in uk",
    "Data Science in UK",
    "MBBS in Canada",
    "MBBS in Saudi Arabia",
    "Study in China",
    "MBA in China",
    "US Student Visa",
    "MBBS in UK For Pakistani Students",
    "Fashion Degrees UK",
  ],
  Visa: [
    "Singapore Visit Visa",
    "Dubai Visit Visa",
    "Indonesia Visit Visa",
    "Work Visa For Australia From Pakistan",
    "Australia Spouse Visa From Pakistan",
    "Kenya Visit Visa",
    "Sri Lanka Visit Visa",
    "Canada Spouse Visa",
    "Canada Study Visa",
    "Tajikistan Visit Visa",
    "Thailand Visit Visa",
    "Germany Work Visa From Pakistan",
    "UK Sole Representative Visa",
    "Canada Work Visa",
    "Malaysia Visit Visa",
    "Azerbaijan Visit Visa",
    "E2 Visa USA",
    "EB1 Visa USA From Pakistan",
    "UK Spouse Visa",
    "China Visit Visa From Pakistan",
    "Uzbekistan Visit Visa",
    "Turkey Visit Visa",
    "Cambodia Visit Visa",
    "Pakistan Visa",
    "Umrah Visa",
    "Vietnam Visit Visa",
    "Student Visa",
    "Uk Visit Visa",
    "Canada Visit Visa",
    "Us Visit Visa",
    "Australia Visit Visa",
    "Spain Visit Visa",
    "New Zealand Visit Visa",
    "Uk Work Visa From Pakistan",
    "Saudi Arabia Visit Visa",
    "Kazakhstan Visit Visa",
    "Dubai Visa Price in Pakistan",
    "Schengen Visa From Pakistan",
    "Canada Visa Consultant in Islamabad Pakistan",
    "UK Visa Consultant in Islamabad Pakistan",
    "Umrah Visa Agent in Islamabad",
    "Umrah Visa Agent in Lahore",
  ],
  "World Tours": [
    "Russia Tour",
    "Malaysia Tour",
    "Vietnam Tour",
    "Azerbaijan Tour",
    "Turkey Tour",
    "Maldives-package",
    "Srilanka Tour",
    "Singapore Tour",
    "Dubai Tour",
    "UAE Tour Packages From Pakistan",
    "Uzbekistan Tour",
    "Baku Tour Package",
    "Thailand Tour Package",
    "Baku Tour",
  ],
  "Pakistan Tours": [
    "Bahrain Valley Swat",
    "Naran-Hunza-Khunjerab-Pass",
    "Skardu Tour",
    "Sarfaranga Jeep Ralley",
    "Swat Chitral Kalash Valley Tour",
    "Fairy Meadows Tour Package",
    "Naran Valley Tour",
    "Naran Kaghan Tour",
    "3 Days Naran Shogran Tour",
    "Swat-Malam Jabbah-Kalam",
    "K2 Base Camp",
    "Chilam Joshi Kalash Spring Festival",
    "Shandur Polo Festival",
    "Swat Valley Tour Package",
    "Azad Kashmir Tour Package",
    "Hunza Valley 6 Days Group Tour",
    "Top Ten Cities in Pakistan",
    "Sikh Yatra Pilgrimage 2025",
    "Salt Mines Khewra / Katas Raj Temples",
    "Kaghan Valley Group Tour",
    "Gilgit-Baltistan Tour Package",
    "Fairy Meadows, Skardu and Hunza",
    "Fairy Meadows, Skardu",
    "Skardu & Hunza Valley Tour",
    "Naran Tour-Hunza Tour - 10 Days",
    "Naran Tour - Hunza - Naltar",
    "Gilgit-Baltistan Tour By Air",
    "Hunza Valley Tour / 7 Nights 8 Days",
    "Naran Valley Gilgit Tour",
    "Swat, Kaghan & Hunza 9 Days",
    "Chitral Valley",
    "Nathiagali Tour",
  ],
  "About Us": ["Company Profile", "Bank Details", "Franchise Registration"],
};
